### ISSUE TITLE
Cant use the program, save folders shows S instead of Local

### ISSUE THREAD

**Issue by UriElPelaoOficial** [LIPtoH/TS-SE-Tool#101]
![image](https://github.com/LIPtoH/TS-SE-Tool/assets/110852375/8b4986ea-cc07-4f46-afb3-9387cfc63ae0)
 how can i set my save folder to local, even if steam cloud is disabled

**Comment by Snitrxm** [comment]
Yoo, the creator of this tool does not give support anymore, btw im creating mine, if it sounds good send me a message in discord.
Discord: snitrxm
