### ISSUE TITLE
Does not work with ATS 1.49

### ISSUE THREAD

**Issue by Wolf68k** [LIPtoH/TS-SE-Tool#105]
Using v0.3.10.1 
I get a warning when trying to load a save from ATS 1.49.

Savefile version 74 is NOT TESTED.

**Comment by Wolf68k** [comment]
Why was this closed? Is there a new version that makes this work with 1.49? I'm confused.

**Comment by LIPtoH** [comment]
New version of Game with new features. Most probably it won't work.
And new version of TS SET was tested and will be released today.
