### ISSUE TITLE
Wrong Distance calculation while adding Custom Job

### ISSUE THREAD

**Issue by ameyagokhale** [LIPtoH/TS-SE-Tool#13]
Hello @LIPtoH 
While adding custom Freight Market Job, the distance is always set to 5km. Actual in-game distance between the cities is not taken into account.
https://imgur.com/KjO06Iv

**Comment by BearcameronUK** [comment]
+1 Probably helpful, but add the job to game, seen the job was add then save reload a new job start and end the same with the same fright as I seen on a previous post it get info from the save game. On Version 0.2.3.2

**Comment by Daynaanlo** [comment]
> Hello @LIPtoH
> While adding custom Freight Market Job, the distance is always set to 5km. Actual in-game distance between the cities is not taken into account.
> https://imgur.com/KjO06Iv

I have exactly the same problem and I use ver: TS.SE.Tool.0.2.5.2 and get 5 km anyway when I make an assignment.
