### ISSUE TITLE
Moving a truck with cargo

### ISSUE THREAD

**Issue by Dancbeunny98** [LIPtoH/TS-SE-Tool#16]
When moving a load to a truck through the program, the load rises to one static position for any event and sometimes it is not convenient. For example, you take a load and want to move it towards you in such a way that it is directed exactly parallel to your truck, but it is not (

При перемещении груза к грузовику через программу, груз встает в одно статичное положение при любом событии и иногда это не удобно. К примеру ты берешь груз и хочешь перемести его к себе таким образом, чтобы он был направлен ровно паралельно твоему грузовику, но это не так(

**Comment by LIPtoH** [comment]
Can't be easily done.
