### ISSUE TITLE
TS-SE-Tool Ats Not Working 

### ISSUE THREAD

**Issue by dean-lowfps** [LIPtoH/TS-SE-Tool#18]
So i recently use this tool for edit my ets2 save data , ets2 save data is working, so i buy ats , so when i tried to edit my ats save data 
there is say no profiles found
![Screenshot_1](https://user-images.githubusercontent.com/72694215/95678663-3a217c00-0bf8-11eb-8218-aef0fddca87f.png)
so i tried to fix that with add custom folder so i tried to add my profile folder then it shows this
![Screenshot_2](https://user-images.githubusercontent.com/72694215/95678704-8e2c6080-0bf8-11eb-8fb9-b1e296feef4b.png)
can someone help me or the developer fix this, this is not important cause i can enjoy with ets2

**Comment by BamButz** [comment]
It seems that with update 1.38 they changed the location for steam profiles.
I changed the path from remote/profiles to steam_profiles and the profiles were shown again, unfortunately there are additional errors

**Comment by adroslice** [comment]
I am unable to add steam_profiles as a custom folder, the folder selection dialogue works, but the radio buttons and the "Add" button remain greyed out.

**Comment by BamButz** [comment]
> I am unable to add steam_profiles as a custom folder, the folder selection dialogue works, but the radio buttons and the "Add" button remain greyed out.

I have to add that i did change to path through code, that functionality to add custom folders did not work for me either.

**Comment by pgfiore** [comment]
AFAIK the tool looks for the InstallPath onto HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam
However, in my Win10 x64 version 2004 the key is: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam
Best

**Comment by LIPtoH** [comment]
@dean-lowfps @adroslice @BamButz 
Steam folders in Docments contains only settings files. Save file leaves in "...\Steam\userdata\...\227300..."
Because of that program doesn't let you add such folders =) (it looks for profile\save files)

@pgfiore 
Some recent changes in Steam added "ac" folder.
Fixed.

**Comment by robe1109** [comment]
The profile does not load for me, can someone help me, I have already deleted everything and installed everything again and nothing
