### ISSUE TITLE
The tiniest sin

### ISSUE THREAD

**Issue by pgfiore** [LIPtoH/TS-SE-Tool#19]
IMHO the second comment line is wrong :-)

        private void DetectGame()
        {
            try
            {
                //Searching for ETS2
                Process[] ets2proc = Process.GetProcessesByName("eurotrucks2");

                //Searching for **ETS2**
                Process[] atsproc = Process.GetProcessesByName("amtrucks");

Best
pf

**Comment by LIPtoH** [comment]
Done =)
