### ISSUE TITLE
Can`t find any profile and can't open custom folder

### ISSUE THREAD

**Issue by SirSoto25** [LIPtoH/TS-SE-Tool#21]
When I start the program, a window appear with the message "no profiles found".

I try to add a custom folder but appeared the following window and can't load the folder

![image](https://user-images.githubusercontent.com/34039951/97239718-9c7b9e80-17ec-11eb-85f4-e8b956f3504f.png)

**Comment by DJOS420** [comment]
I have been having the same issue.
