### ISSUE TITLE
Doesn't recognise new DLC

### ISSUE THREAD

**Issue by LegalSmeagol** [LIPtoH/TS-SE-Tool#25]
Program doesn't recognise newly purchased and installed DLC. I have reinstalled the program, regenerated the files, reinstalled the game, deactivated/reactivated my DLCs and no bueno.

Had a very high opinion until this fundamental feature clearly flaws the entire program.

**Comment by sirlupusdev** [comment]
The program recognizes the things that are inside the save folders no matter which DLCs etc. you have. To be sure, did you create the profiles before you purchased the DLCs?

I currently cannot confirm this bug, it works fine for me.
