### ISSUE TITLE
Program only visible in task manager

### ISSUE THREAD

**Issue by Milzerrr** [LIPtoH/TS-SE-Tool#27]
![Screenshot_8](https://user-images.githubusercontent.com/81829689/113449469-2f54e080-93fe-11eb-84a6-f28fead6e1f8.jpg)

**Comment by ScooterGamingTV** [comment]
having same issue also the program not responding and no errors
![Screenshot_2](https://user-images.githubusercontent.com/93406774/162592767-fe6e83f0-6d3a-48a9-8e66-3de3292daae5.png)

**Comment by ghost** [comment]
Same problem here :-(

**Comment by Optimusiakkk** [comment]
Same, I turned off all antiviruse and it didn't worked for me.

**Comment by DziwiszPL** [comment]
Same issue here.
![Screenshot 2023-05-31 000100](https://github.com/LIPtoH/TS-SE-Tool/assets/135072871/5a567f80-5c94-4dc4-9a18-3c91c770e54a)
![Screenshot 2023-05-31 000153](https://github.com/LIPtoH/TS-SE-Tool/assets/135072871/d372a413-cf48-4f6d-956c-336ba3e79f43)

**Comment by DziwiszPL** [comment]
Issue still exists, same thing in 0.3.11.0
![image_2023-12-06_111152315](https://github.com/LIPtoH/TS-SE-Tool/assets/135072871/7759aaba-16f8-4452-9d3a-5745057f7849)
@LIPtoH Care to elaborate how did you fix the issue by closing this ticket, or at least try to help?
