### ISSUE TITLE
Negative money values not shown

### ISSUE THREAD

**Issue by Iskatu** [LIPtoH/TS-SE-Tool#31]
Saves with negative money values show '0$', and loading them gets an exception:
![image](https://user-images.githubusercontent.com/15678302/127404905-6d8d2462-abef-49f3-8a16-3bb3c611d874.png)

**Comment by Titanic4** [comment]
I think that's related to the fact that this program uses unsigned 32-bit integer while ETS2 and ATS uses signed 64-bit long value to store profile's money. The program tries to parse 64-bit long value as unsigned 32-bit integer. If the amount of money is less than 0 or its larger than 2^32, the exception will be thrown once the program tries to parse the value.
