### ISSUE TITLE
[v0.2.7.0] Error whilst saving edited game save

### ISSUE THREAD

**Issue by JaffaKetchup** [LIPtoH/TS-SE-Tool#41]
**Error: 'The given key was not present in the dictionary.'**
Loading save file works correctly. Application crashed and corrupts existing save file when trying to save.

Am updated to the latest version v0.2.7.0 after doing clean re-install from previous version.

[errorlog](https://github.com/LIPtoH/TS-SE-Tool/files/7532623/errorlog.log) attached.

**Comment by LIPtoH** [comment]
Fixed
