### ISSUE TITLE
Cannot edit Steam Cloud Profiles

### ISSUE THREAD

**Issue by lupus0802** [LIPtoH/TS-SE-Tool#42]
Hello, when I try to edit a profile synchronized with steam cloud, the program says that I need to disable steam Cloud.
![ETS2 Profile Editor issue](https://user-images.githubusercontent.com/87112805/147914308-5485bfc8-cbb5-46a9-a510-143077a3cf51.jpg)

Is steam cloud editing temporarily disabled and do I need to convert the profile to a local one?

Thanks in advvance

**Comment by LIPtoH** [comment]
You need to convert the profile to a local one

**Comment by Felzow47** [comment]
> You need to convert the profile to a local one

how to convert in local profile ?

**Comment by Neutrovertido** [comment]
Since the dev didn't mention how to do it...

@lupus0802 you can change it in this screen in the 'manage profiles' section, afterwards the program should allow you to edit the save.
![image](https://user-images.githubusercontent.com/61665012/183238441-1c33cc9c-7eb0-4af8-9ec5-4da571a7c8d6.png)
