### ISSUE TITLE
Issues with translation + level/skills editing doesn't work

### ISSUE THREAD

**Issue by GoTVm** [LIPtoH/TS-SE-Tool#47]
The translation file from English to Italian is kind of lackluster. Some translations don't make much sense in context, while there are also some mistakes. I fixed a couple of them in the file (which I'm willing to share in a fork so this issue can be fixed), but I also noticed that some parts of the form don't translate at all regardless of language, namely the "Truck" button and all the Trailer settings buttons. I took a peek into the code, but I'm not a C# developer so I couldn't do much.

Another issue I found out is editing level and skills, which straight up does not work. I tried editing level and skills alone, then adding/removing money to confirm that the save was being edited, but neither attemps worked.

**Comment by ZaNeksuto** [comment]
Same thing happened to me

**Comment by VamsiVK35** [comment]
I have same issue with editing player level and skills, it doesn't even work. Even when I open the save file immediately after editing the save file it is not showing what I changed.

**Comment by ThatTonybo** [comment]
Can confirm the same issue: money works but levels and skills don't work

**Comment by VamsiVK35** [comment]
But I tried the previous version, in that the skills and levels works. So used the previous version for the levels and skills and the latest version for the rest of it. Try the previous version for this issue.

**Comment by GoTVm** [comment]
I imagined you could go back to a previous working version, it's just that this version (I haven't seen any of the previous) is so not refined and poorly kept together. The developer also doesn't seem to contribute much anymore either, this GitHub version appears to be older than the one found on external forums. I wish the developer were more in the picture so other people could suggest what to fix since this seems to be the only tool that allows this type of modifications.

**Comment by LIPtoH** [comment]
Fixed with new version.

Translation can be sent via email.
