### ISSUE TITLE
A feature to unlock Truck Dealers and Recruitment Agencies on the map

### ISSUE THREAD

**Issue by kyler1cartesis** [LIPtoH/TS-SE-Tool#49]
Please add a feature to unlock them alongside unlocking cities, it will be very helpful. Also add a check to highlight them all and open them at the same time. Thanks.

**Comment by LIPtoH** [comment]
1) Truck Dealers and Recruitment Agencies unlock not possible. (no data about them is stored in save file)
2) "add a check to highlight them all and open". If you've read the help file, you know that clicking on buttons with no items selected is the same as selecting all
