### ISSUE TITLE
Not Responding Issue,

### ISSUE THREAD

**Issue by ranrhos** [LIPtoH/TS-SE-Tool#63]
When I open the .exe file, it decides to be like 'Hey, i dont want to work, bye.'. So it just goes and does a Not responding loop everytime I try to open it.

**Comment by LIPtoH** [comment]
Check your antivirus software. It's probably blocking it because the Tool is looking for a registry entry of a Steam folders.

**Comment by 150L** [comment]
Alright, thank you.

**Comment by ranrhos** [comment]
Thank you.

**Comment by Optimusiakkk** [comment]
I have same problem, and It didn't worked for me
