### ISSUE TITLE
Can`t edit profile in the game

### ISSUE THREAD

**Issue by qiqiqi12345** [LIPtoH/TS-SE-Tool#64]
After I use the tool,i`t worked,but  I cannot edit the profile in the game. Once I do this, the game will not respond
My ETS2 vision is 1.45,and the tool vision is 0.3.7.2

**Comment by LIPtoH** [comment]
1. Always update to latest version.
2. Do not edit autosaves.
3. You can Restore from Backup (button next to save selection)
