### ISSUE TITLE
Garages/Visited Cities State/Country Codes Not Showing

### ISSUE THREAD

**Issue by psdbudd** [LIPtoH/TS-SE-Tool#73]
Hi there,

So sometimes the formatting of the tool's cities/states/country codes doesnt show up or is a words are added. Mind you i have all map dlcs as of currently at writing this issue.

Can you see how to fix this.
![Steam Client Info](https://user-images.githubusercontent.com/47226933/197018352-5558a43d-b010-4a4e-8573-c2af5b716838.PNG)
![TSSE Tool Issue 1](https://user-images.githubusercontent.com/47226933/197018353-765f36cf-76f2-4095-ad42-891dc18d9cf6.PNG)
![TSSE Tool Issue 2](https://user-images.githubusercontent.com/47226933/197018354-3f9686cb-e0ae-403e-a7dc-0e5f3f12101a.PNG)

**Comment by LIPtoH** [comment]
It relies on included dictionaries and not on data in save file. So with mods and newly added cities it became outdated fast.
