### ISSUE TITLE
Map exploration data merge request.

### ISSUE THREAD

**Issue by oubeidong** [LIPtoH/TS-SE-Tool#76]
Data can be embedded in TS-SE-Tool. Please check out the following links.
https://steamcommunity.com/sharedfiles/filedetails/?id=2851462342
https://steamcommunity.com/sharedfiles/filedetails/?id=2851483166

**Comment by LIPtoH** [comment]
Data will change from update to update. And only valid for standard game without map mods. 
It would be better if you can scan memory for map data directly.
So i don't want to add static map data.
