### ISSUE TITLE
Program interface/UI doesn't show Load button

### ISSUE THREAD

**Issue by anolting** [LIPtoH/TS-SE-Tool#81]
Hi Kirill

i've just downloaded your TS-SES_Tool in version 0.3.8.1.
After starting up I've read your documentation to figure out how the program works. 
I noticed two things which are different from the section "Using tool". First the tool is able to find my game.sii and shows the correct data stored in the file, e.g. my profile, comany etc. But when it comes to load it, the load button is not shown. As a result for instane the Tab Profile shows only grayed out skills.
Instead of a Load button I find a textbox (also grayed out) saying "Disable Steam Cloud". I'm not sure if this should be a button too, but it is not clickable.

Do you have an idea what is wrong, if so?

Best Alex

The UI in the documentation looks like this:

![grafik](https://user-images.githubusercontent.com/12763750/223261328-4d548493-e859-43d9-babb-a5314d314b92.png)

The UI of the current version of the program running on my PC looks like this:

![grafik](https://user-images.githubusercontent.com/12763750/223263363-36bfe0d9-2143-48e8-926c-a71854c0c141.png)

**Comment by sirlupusdev** [comment]
You will have to disable Steam Cloud Saving for that profile in-game (Main Menu -> Manage/Edit Profile). After editing with this tool you can turn that on again.

**Comment by anolting** [comment]
Sorry for the long delay. Thanks for your help. It works. 
We are good to close this issues.
