### ISSUE TITLE
TS SE not responding

### ISSUE THREAD

**Issue by Crisstiian2303** [LIPtoH/TS-SE-Tool#82]
i start the program and it starts the update checker, i click on "ok" and then the ts.se it freezes on the start of the application.
I have try to desactivate my antivirus and still don't works
[log.log](https://github.com/LIPtoH/TS-SE-Tool/files/11057866/log.log)

https://user-images.githubusercontent.com/124546177/227407866-1526bc64-449f-4d68-b3c3-2ae23e86c8c6.mov

**Comment by sirlupusdev** [comment]
The log is complaining about the config missing or having the wrong format, even tho its there. Can you try deleting the configuration file or deleting the entire folder and re-downloading it from the latest release on GitHub?

**Comment by Crisstiian2303** [comment]
it still not works, i have try to download an older version but does the same like in the video. i have download "dotnetversions" to see my actual version of .net and i have those versions
![image](https://user-images.githubusercontent.com/124546177/227626426-5475c50b-efcc-4956-9968-ed653d2749a4.png)

**Comment by Crisstiian2303** [comment]
i have tested out on a vm (oracle vm) and it works fine, anyones knows why?¿
this app register data on appdata or on any folder?¿
![image](https://user-images.githubusercontent.com/124546177/227684292-0ccfe58d-44b4-459f-962e-39a40b151184.png)

**Comment by sirlupusdev** [comment]
You don't have an ETS2 installation in the VM, correct?

**Comment by Crisstiian2303** [comment]
I have already solved it, I had an error in the ets2 folder of the documents folder, basically the error was that a cache folder had been created and that made the program inaccessible
