### ISSUE TITLE
Unable to load/decrypt saves after 1.47 update

### ISSUE THREAD

**Issue by RainBawZ** [LIPtoH/TS-SE-Tool#83]
What the title says

**Comment by sirlupusdev** [comment]
Does it give you a specific error/error code?
Also, yes, might be an issue, as far as I know 1.46 wasn't supported as well, but still worked.

**Comment by drunkmochi** [comment]
This happened to me too, it said file can't be decrypted basically.

**Comment by China-Best** [comment]
如果你使用了一些特殊的，比如轿车，巴士这类给游戏增加额外功能的MOD，就会导致解码失败。须停用之后再解码修改。
（Sorry,I am not good at English.You can try to translate Chinese to English with tools.)

**Comment by drunkmochi** [comment]
Nope, I don't use any mods

**Comment by bisoft2** [comment]
Version 1.47 changed the format of savegame encripted files. I think some tools like this, include this other tool (https://github.com/TheLazyTomcat/SII_Decrypt ) to decode savegame file.

**Comment by AlexKERNEL** [comment]
You can try use my fork of https://github.com/TheLazyTomcat/SII_Decrypt with changes for 1.47 https://github.com/AlexKERNEL/SII_Decrypt_1.5.x

**Comment by RainBawZ** [comment]
> Does it give you a specific error/error code? Also, yes, might be an issue, as far as I know 1.46 wasn't supported as well, but still worked.

The only useful log entries in my log are
`Could not decrypt after 5 attempts`
`Wrongly decoded Save file or wrong file format`

Essentially just saying the same thing as this issue's title

**Comment by AnzhiZhang** [comment]
1.47 have same error message with 1.46, only the save file version are different. But it cannot work on 1.47

**Comment by jorensanbar** [comment]
> You can try use my fork of https://github.com/TheLazyTomcat/SII_Decrypt with changes for 1.47 https://github.com/AlexKERNEL/SII_Decrypt_1.5.x

Perfect! Work with version 3 of files. Thank you!

**Comment by AlexKERNEL** [comment]
We have tested the work of TS-SE-Tool with a new SII_Decrypt.dll x86 from patch with 1.47 support  
https://github.com/AlexKERNEL/SII_Decrypt_1.5.x/blob/master/Library/Delphi/Release/win_x86/SII_Decrypt.dll

With new DLL, files of 1.47 are decrypted without problems.

But, if you make changes to the save via the utility, the save will be broken and not be loaded in the game.
In order for making changes to work correctly, I think it is necessary to implement a class for the police_offence_log parameter.
