### ISSUE TITLE
My computer cannot open software

### ISSUE THREAD

**Issue by ManagerAn** [LIPtoH/TS-SE-Tool#94]
![I 6YD3ORMY6`@PS )RD~%28](https://github.com/LIPtoH/TS-SE-Tool/assets/135213079/db1613a3-b0db-4111-89fb-998333380cac)
My computer cannot open software，I have cancelled the cloud archive and checked the integrity of the archive, which is available,

**Comment by sirlupusdev** [comment]
Please verify that the correct location of the ETS2 folder is set in the application's settings.
